theme: jekyll-theme-minimal
title: California Model Aerospace
description: Cost-efficient model rocketry kits and components plus other aerospace projects.
logo: /photos/CMALogo.png
show_downloads: false
